- hosts: vm
  ignore_unreachable: true
  tasks:
    - name: creating a empty file
      file:
        path: "/home/snowman/felixstrauss.txt"
        state: touch
        owner: snowman
    - name: Install packages
      ansible.builtin.apt:
        name:
              - nginx
              - git
        state: latest
    - name: Add Docker GPG signing key
      ansible.builtin.apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    - name: Install Docker
      ansible.builtin.apt:

        name: docker-ce
        state: latest
    - name: Check if Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        register: docker_status
    - name: Add user to Docker group
      ansible.builtin.user:
          name: snowman
          groups: docker
          append: yes
    - name: Test "hello-world" container
      ansible.builtin.docker_container:
          name: hello-world
          image: hello-world
          state: started



