apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx.yml
images:
  - name: felixstrauss
    newName: devops2022.azurecr.io/felixstrauss:6f8bcb363098defcfac9a2e18ed76c0a8508f149
