- name: working on vm frosty
  hosts: vm
  become: true
  tasks: 
    - name: Install the packages dependencies
      ansible.builtin.apt:
        name: 
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
        state: latest
        update_cache: true

    - name: add docker apt key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal state
        state: present
    - name: test docker rep susseccfull
      ansible.builtin.shell: sudo apt-cache policy | grep docker
