- name: working on vm frosty
  hosts: vm
  become: true
  tasks: 
    - name: Install the packages dependencies #Installation of dependencies
      ansible.builtin.apt:
        name: 
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
        state: latest
        update_cache: true

    - name: add docker apt key #add key to download the right Docker and not a Virus
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings

    - name: Add specified repository into sources list #add repository in source list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal state
        state: present

    - name: test docker rep susseccfull #check if it's downloaded
      ansible.builtin.shell: cat "/etc/apt/sources.list.d/Docker.list"
      register: dockerrepo
      failed_when: dockerrepo.stderr != ''
      changed_when: false
    
    -name: apt-get update
     ansible.builtin.shell: sudo apt-get update

    - name: docker plugins #installieren der plugins docker
      ansible.builtin.apt: 
        name:
          - docker-ce  
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Check if Docker is running #check if docker is running
      ansible.builtin.service: dpkg -l 'docker-ce' dpkg -l 'docker-ce-cli' dpkg -l 'containerd.io' dpkg -l 'docker-compose-plugin'
      register: dockercomponents
      failed_when: dockercomponents.stderr != ''
      changed_when: false
    
    -name: Check is Docker running
     ansible.builtin.service:
      name: docker
      state: started
