- hosts: vm
  ignore_unreachable: true
  tasks:
    - name: creating a empty file
      file:
        path: "/home/snowman/felixstrauss.txt"
        state: touch
        owner: snowman
    - name: Install packages
      ansible.builtin.apt:
        name:
              - nginx
              - git
        state: latest
   
