- name: working on vm frosty
  hosts: vm
  become: true
  tasks: 
    - name: Install the packages dependencies #Installation of dependencies
      ansible.builtin.apt:
        name: 
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
        state: latest
        update_cache: true

    - name: add docker apt key #add key to download the right Docker and not a Virus
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings

    - name: Add specified repository into sources list #add repository in source list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal state
        state: present

    - name: test docker rep susseccfull #check if it's downloaded
      ansible.builtin.shell: sudo apt-cache policy | grep docker
      register: dockerrepo
      failed_when: dockerrepo.stderr != ''
      changed_when: false
    
    - name: docker plugins #installieren der plugins docker
      ansible.builtin.shell: 
        name:
          - docker-ce  
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin
        register: dockercomponents
        failed_when: dockercomponents.stderr != ''
        changed_when: false

    - name: Check if Docker is running #check if docker is running
      ansible.builtin.service: dkpg -1 'docker-ce' dkpg -1 'docker-ce-cli' dkpg -1 'containerd.io' dkpg -1 'docker-compose-plugin'
      register: dockercomponents
      failed_when: dockercomponents.stderr != ''
      changed_when: false
