- name: working on vm frosty
  hosts: vm
  tasks: 
    - name: Install the packages dependencies
      ansible.builtin.apt:
        name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        state: latest
        update_cache: true
