- name: working on vm frosty
  hosts: vm
  become: true
  tasks: 
    - name: Install the packages dependencies #Installation of dependencies
      ansible.builtin.apt:
        name: 
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
        state: latest
        update_cache: true

    - name: check if dependencies are installed
      ansible.builtin.shell: dpkg -l 'ca-certificates' && dpkg -l 'curl' &&  dpkg -l 'gnupg' && dpkg -l 'lsb-release'
      register: certificates
      failed_when: certificates.stderr != ''
      changed_when: false

    - name: add keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory 


    - name: add docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal state
        state: present

    - name: check added docker repository
      ansible.builtin.shell: cat "/etc/apt/sources.list.d/Docker.list"
      register: dockerrepo
      failed_when: dockerrepo.stderr != ''
      changed_when: false
    
    - name: apt-get update
      ansible.builtin.shell: sudo apt-get update

    - name: Install the package "docker"
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin
        state: latest

    - name: check if docker components are installed
      ansible.builtin.shell: dpkg -l 'docker-ce' && dpkg -l 'docker-ce-cli' &&  dpkg -l 'containerd.io' && dpkg -l 'docker-compose-plugin'
      register: dockercomponents
      failed_when: dockercomponents.stderr != ''
      changed_when: false
    
